# site settings
title: Ken
subtitle: Lee
email: admin@kleetax.ca
description: The best person to get your taxes done with
baseurl: "/kleetax" # the subpath of your site, e.g. /blog
url: applesilicon1.github.io # the base hostname & protocol for your site
author:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/klee.tax/
  LinkedIn: https://www.linkedin.com/in/kenyhlee
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
